// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8XJ7IwSQHwKZL9E2iPOY5swQ3DjJbbsA',
    appId: '1:120136281734:web:b33434243106855603ab07',
    messagingSenderId: '120136281734',
    projectId: 'pushnoti-55f58',
    authDomain: 'pushnoti-55f58.firebaseapp.com',
    storageBucket: 'pushnoti-55f58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq8w2G5qYJqwReqbUI-IJ0D9qshz83sDE',
    appId: '1:120136281734:android:deaa8d1ecb16dd7c03ab07',
    messagingSenderId: '120136281734',
    projectId: 'pushnoti-55f58',
    storageBucket: 'pushnoti-55f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyjQIFxYwEvIp0TgALMutf9ezCctno_64',
    appId: '1:120136281734:ios:8b9702a0cfe776e803ab07',
    messagingSenderId: '120136281734',
    projectId: 'pushnoti-55f58',
    storageBucket: 'pushnoti-55f58.firebasestorage.app',
    iosBundleId: 'com.example.pushnoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyjQIFxYwEvIp0TgALMutf9ezCctno_64',
    appId: '1:120136281734:ios:8b9702a0cfe776e803ab07',
    messagingSenderId: '120136281734',
    projectId: 'pushnoti-55f58',
    storageBucket: 'pushnoti-55f58.firebasestorage.app',
    iosBundleId: 'com.example.pushnoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8XJ7IwSQHwKZL9E2iPOY5swQ3DjJbbsA',
    appId: '1:120136281734:web:513f12b65d76568703ab07',
    messagingSenderId: '120136281734',
    projectId: 'pushnoti-55f58',
    authDomain: 'pushnoti-55f58.firebaseapp.com',
    storageBucket: 'pushnoti-55f58.firebasestorage.app',
  );
}